### ISSUE TITLE
how to organize github site

### ISSUE THREAD

**Issue by cmlegault** [pdbsimproj/WoodsHoleSimThing#2]
Need to decide whether to allow all of us to make commits to master directly, or require pull requests from us that can be OKed by one person overseeing all code. Latter is more typical of large programming projects, but could lead to having forks of the project in our regular github sites (at least temporarily). Not sure which is more important.

**Comment by pdbsimproj** [comment]
My opinion: we should all be able to commit directly, but maybe institute the testing thingy that was mentioned at our initial meeting? Quality control is important, but it is always hard to make progress on these group things - I think having an overseerer will slow us down.

**Comment by cmlegault** [comment]
Sounds good to me. Can you add cmlegault to the contributors list? https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by cmlegault** [comment]
Done - thanks Dan!
